Repository basnijholt/adaptive-lighting, pull requests merged in 2023-04, with the labels that each got.

#487 Add auto_reset_manual_control with async timer
  .github/workflows/update-readme.yml
  README.md
  custom_components/adaptive_lighting/const.py
  custom_components/adaptive_lighting/services.yaml
  custom_components/adaptive_lighting/strings.json
  custom_components/adaptive_lighting/switch.py
  tests/test_switch.py
Labels: popularity-high, kind/enhancement

#87 Continue to adapt color temperature down to the sleep temperature after sunset
  README.md
  custom_components/adaptive_lighting/const.py
  custom_components/adaptive_lighting/strings.json
  custom_components/adaptive_lighting/switch.py
Labels: popularity-medium, status/done+waiting-for-review

#460 Basic community fixes PR
  custom_components/adaptive_lighting/services.yaml
  custom_components/adaptive_lighting/switch.py
  tests/test_switch.py
Labels: status/done+waiting-for-review

#510 Correctly wait for transitions
  custom_components/adaptive_lighting/manifest.json
  custom_components/adaptive_lighting/switch.py
  tests/test_switch.py
Labels: status/done+waiting-for-review

#514 Fix RGB Color Temp Swaps
  custom_components/adaptive_lighting/switch.py
  tests/test_switch.py
Labels: status/done+waiting-for-review

#513 Refactor `_adapt_lights` into `_update_manual_control_and_maybe_adapt`
  custom_components/adaptive_lighting/manifest.json
  custom_components/adaptive_lighting/switch.py
Labels: status/done+waiting-for-review

#565 Refactor `_supported_features`
  custom_components/adaptive_lighting/const.py
  custom_components/adaptive_lighting/switch.py
Labels: status/done+waiting-for-review
